### ISSUE TITLE
Orchestrator not found needs a better error message

### ISSUE THREAD

**Issue by anthonychu** [Azure/azure-functions-durable-js#120]
**Describe the bug**
When attempting to start an orchestration that doesn't exist, the error returned is not useful

**Investigative information**

- Durable Functions extension version: 2.0.0
- durable-functions npm module version: 1.3.1
- Language (JavaScript/TypeScript) and version: JS
- Node.js version: 10.16.3

**To Reproduce**

1. Clone this repo: https://github.com/anthonychu/test-durable-js
1. ```bash
    npm i
    func extensions install
    cp local.settings.SAMPLE.json local.settings.json
    # Add storage connection string to local.settings.json
    func start
    ```
1. Attempt to start a non-existent orchestrator: `http://localhost:7071/api/orchestrators/foo`.
1. A 500 error is returned and the function logs an error message that doesn't explain the problem:
    ```
    [2019-11-17 7:00:36 AM] Executed 'Functions.DurableFunctionsHttpStart' (Failed, Id=03d3aa5b-23f2-4ca3-b0de-a282adb4a52d)
    [2019-11-17 7:00:36 AM] System.Private.CoreLib: Exception while executing function: Functions.DurableFunctionsHttpStart. System.Private.CoreLib: Result: Failure
    [2019-11-17 7:00:36 AM] Exception: Error: [object Object]
    [2019-11-17 7:00:36 AM] Stack: Error: [object Object]
    [2019-11-17 7:00:36 AM]     at DurableOrchestrationClient.<anonymous> (/Users/antchu/source/temp/test-durable-js/node_modules/durable-functions/lib/src/durableorchestrationclient.js:340:43)
    [2019-11-17 7:00:36 AM]     at Generator.next (<anonymous>)
    [2019-11-17 7:00:36 AM]     at fulfilled (/Users/antchu/source/temp/test-durable-js/node_modules/durable-functions/lib/src/durableorchestrationclient.js:4:58)
    [2019-11-17 7:00:36 AM]     at process._tickCallback (internal/process/next_tick.js:68:7).
    ```

@ConnorMcMahon @cgillum

**Comment by antempus** [comment]
Jumping on to this with some addition information: 

While this seems to be unique to HTTP Triggered Clients, if you're using another invocation mechanism (cron/cosmos/etc) and if the activity or subOrchestrator is ill-defined, the runtime steps over the offending line(s) and continues execution without error.

**Comment by anthonychu** [comment]
Closing because it's a duplicate of #53.

@antempus What you're running into might be something else to investigate. Can you create a new issue for it? Thanks.
