### ISSUE TITLE
Durable HTTP trigger fails to start

### ISSUE THREAD

**Issue by slyons** [Azure/azure-functions-durable-js#27]
Using the default code when deploying a new instance of a functions App I get the following error when trying to start the HTTP trigger function:

```
2018-12-06T20:18:51.467 [Error] Executed 'Functions.DurableFunctionsHttpStart1' (Failed, Id=af5b1e03-a723-437f-bb3c-b43ef08570cb)
Result: Failure
Exception: Error: [object Object]
Stack: Error: [object Object]
    at DurableOrchestrationClient.<anonymous> (D:\home\site\wwwroot\node_modules\durable-functions\lib\src\durableorchestrationclient.js:176:23)
    at Generator.next (<anonymous>)
    at fulfilled (D:\home\site\wwwroot\node_modules\durable-functions\lib\src\durableorchestrationclient.js:4:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

I have installed version 1.1.2

**Comment by kashimiz** [comment]
Thank you for reporting this, @slyons . Can you share what version of Microsoft.Azure.WebJobs.Extensions.DurableTask your function app is using?

**Comment by slyons** [comment]
Whatever version is installed through the portal by default.

**Comment by kashimiz** [comment]
Thank you. It looks like the webhook used to start the orchestration is returning an error code, causing DurableOrchestrationClient to throw an error. A common cause of this is trying to call your durable functions orchestrator using the wrong endpoint. It's recommended you use the endpoint provided by clicking on the `< / > Get functions URL` text, replacing the bracketed text with your orchestrator function's name.

**Comment by sckelly** [comment]
I'm also getting this issue in my deployment, when calling OrchestratorFunction from Postman I get a 500 Internal Server Error and that is with the </>Get Function URL section. :crying_cat_face: 

When calling from the "Run" snippet on my Azure Resource Group. and Putting in OrchestratorFunction in the params section, get a `URL is not defined error` which you have mentioned K :smile_cat: 

Not sure how to proceed with deploy for now, but open to trying things in this discussion.

**Comment by kashimiz** [comment]
@sckelly, re: the `URL is not defined` error, my first question is what version of the `durable-functions` npm package you have installed. `1.1.2` (the latest) fixed a bug in previous versions that would result in that exception.

**Comment by sckelly** [comment]
@kashimiz Updating fixed it! Thanks for that, tried downgrading earlier to debug something else and forgot to reupgrade. Thanks again!

**Comment by kashimiz** [comment]
Closing this issue for now; if you're still experiencing this issue, @slyons, please re-open and we'll resume investigation.

**Comment by hanvyj** [comment]
I'm converting my existing client functions to use the new 1.1.2 functionality and am facing this issue too.

I had the EPROTO error: https://github.com/Azure/azure-functions-durable-js/issues/28

Adding `WEBSITE_HOSTNAME = "http://localhost:7071"` seemed to resolve that issue, but now I'm getting:

```
[08/01/2019 17:01:23] Executed 'Functions.socos-process-test-client' (Failed, Id=d0c4a457-d17a-4903-b57f-45ff8b98fd3f)
[08/01/2019 17:01:23] System.Private.CoreLib: Exception while executing function: Functions.socos-process-test-client. System.Private.CoreLib: Result: Failure
Exception: Error: [object Object]
Stack: Error: [object Object]
    at DurableOrchestrationClient.<anonymous> (D:\Projects\argh\build\socos-process-test-client\index.js:928:23)
    at Generator.next (<anonymous>)
    at fulfilled (D:\Projects\argh\build\socos-process-test-client\index.js:756:58)
    at process._tickCallback (internal/process/next_tick.js:68:7).
```

Like above. I'm using version 1.1.2, and 1.7.0 Durable Tasks extensions. It does say:

```Skipping 'WEBSITE_HOSTNAME' from local settings as it's already defined in current environment variables.```

When I launch with `func start` now.
