### ISSUE TITLE
Exception: The orchestrator can not execute without an OrchestratorStarted event if app uses WebPubSub extension

### ISSUE THREAD

**Issue by hossam-nasr** [Azure/azure-functions-durable-js#409]
There is a bug that sometimes occurs in which running any orchestrator in a DF node app will fail with an error saying "The orchestrator can not execute without an OrchestratorStarted event," as below:

```
Exception: The orchestrator can not execute without an OrchestratorStarted event.
Stack: TypeError: The orchestrator can not execute without an OrchestratorStarted event.
    at Function.ensureNonNull (C:\Users\hossamnasr\ms\azure\durable\js-sdk\lib\src\utils.js:63:19)
    at Orchestrator.<anonymous> (C:\Users\hossamnasr\ms\azure\durable\js-sdk\lib\src\orchestrator.js:45:58)
    at Generator.next (<anonymous>)
    at C:\Users\hossamnasr\ms\azure\durable\js-sdk\lib\src\orchestrator.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\hossamnasr\ms\azure\durable\js-sdk\lib\src\orchestrator.js:4:12)
    at Orchestrator.handle (C:\Users\hossamnasr\ms\azure\durable\js-sdk\lib\src\orchestrator.js:26:16)
    at C:\Users\hossamnasr\ms\azure\durable\js-sdk\lib\src\shim.js:18:22
    at Generator.next (<anonymous>)
    at C:\Users\hossamnasr\ms\azure\durable\js-sdk\lib\src\shim.js:8:71
```

Sometimes, this error may be nested inside an "aggregate error" with a "node exited with code 1" exception, as below: 

```
[2022-12-15T21:21:24.675Z] 2e6aedb50b154c65a82030fc55cc879c: Function 'DurableFunctionsOrchestratorJS1 (Orchestrator)' failed with an error. Reason: System.AggregateException: One or more errors occurred. (node exited with code 1 (0x1))
[2022-12-15T21:21:24.676Z]  ---> Microsoft.Azure.WebJobs.Script.Workers.WorkerProcessExitException: node exited with code 1 (0x1)
[2022-12-15T21:21:24.676Z]  ---> System.Exception: LanguageWorkerConsoleLog[error] Worker f15e65ac-fafd-406c-a4c5-8db145456720 uncaught exception (learn more: https://go.microsoft.com/fwlink/?linkid=2097909 ): TypeError: The orchestrator can not execute without an OrchestratorStarted event.     at Function.ensureNonNull (C:\Users\hossamnasr\ms\azure\test-functions\repro-old\node_modules\durable-functions\lib\src\utils.js:63:19)     at Orchestrator.<anonymous> (C:\Users\hossamnasr\ms\azure\test-functions\repro-old\node_modules\durable-functions\lib\src\orchestrator.js:45:58)     at Generator.next (<anonymous>)     at C:\Users\hossamnasr\ms\azure\test-functions\repro-old\node_modules\durable-functions\lib\src\orchestrator.js:8:71     at new Promise (<anonymous>)     at __awaiter (C:\Users\hossamnasr\ms\azure\test-functions\repro-old\node_modules\durable-functions\lib\src\orchestrator.js:4:12)     at Orchestrator.handle (C:\Users\hossamnasr\ms\azure\test-functions\repro-old\node_modules\durable-functions\lib\src\orchestrator.js:26:16)     at Object.default (C:\Users\hossamnasr\ms\azure\test-functions\repro-old\node_modules\durable-functions\lib\src\shim.js:17:9)     at t.InvocationModel.<anonymous> (C:\Program Files\Microsoft\Azure Functions Core Tools\workers\node\dist\src\worker-bundle.js:2:51947)     at Generator.next (<anonymous>)
```

This occurs when:

1. Using DF with the upcoming node V4 prog model (still not released, see #384)
2. Setting the `EnableWorkerIndexing` feature flag
3. Adding the `Microsoft.Azure.WebJobs.Extensions.WebPubSub` extension to your `.csproj` file
4. Using the WebPubSub extension in your application

See this larger issue for more details: https://github.com/Azure/azure-functions-durable-extension/issues/2338

**Comment by hossam-nasr** [comment]
cc @davidmrdavid

**Comment by hossam-nasr** [comment]
Closed by https://github.com/Azure/azure-sdk-for-net/pull/33130 and https://github.com/Azure/azure-functions-durable-extension/pull/2341

**Comment by ejizba** [comment]
Also mitigated by https://github.com/Azure/azure-functions-host/pull/8900, which may or may not roll out before the extensions are included in a bundle release
