### ISSUE TITLE
Hello world works locally but fails when deployed to Azure

### ISSUE THREAD

**Issue by lilyjma** [Azure/azure-functions-durable-js#570]
I created a JS (Node 18) function app using Programming Model v4 and added a Durable Functions through the template provided. I was able to run the app locally without problems, but after deploying to Azure, I got this error: 

Result: Failure Exception: The operation failed with an unexpected status code: 400. Details: {"Message":"One or more of the arguments submitted is incorrect","ExceptionMessage":"The function 'durableHelloHttpStart' doesn't exist, is disabled, or is not an orchestrator function. Additional info: The following are the known orchestrator functions: 'durableHelloOrchestrator'.","ExceptionType":"System.ArgumentException","StackTrace":" at Microsoft.Azure.WebJobs.Extensions.DurableTask.DurableTaskExtension.ThrowIfFunctionDoesNotExist(String name, FunctionType functionType) in D:\\a\\_work\\1\\s\\src\\WebJobs.Extensions.DurableTask\\DurableTaskExtension.cs:line 1338\r\n at Microsoft.Azure.WebJobs.Extensions.DurableTask.DurableClient.Microsoft.Azure.WebJobs.Extensions.DurableTask.IDurableOrchestrationClient.StartNewAsync[T](String orchestratorFunctionName, String instanceId, T input) in D:\\a\\_work\\1\\s\\src\\WebJobs.Extensions.DurableTask\\ContextImplementations\\DurableClient.cs:line 180\r\n at Microsoft.Azure.WebJobs.Extensions.DurableTask.HttpApiHandler.HandleStartOrchestratorRequestAsync(HttpRequestMessage request, String functionName, String instanceId) in D:\\a\\_work\\1\\s\\src\\WebJobs.Extensions.DurableTask\\HttpApiHandler.cs:line 875\r\n at Microsoft.Azure.WebJobs.Extensions.DurableTask.HttpApiHandler.HandleRequestAsync(HttpRequestMessage request) in D:\\a\\_work\\1\\s\\src\\WebJobs.Extensions.DurableTask\\HttpApiHandler.cs:line 306"} Stack: Error: The operation failed with an unexpected status code: 400. Details: {"Message":"One or more of the arguments submitted is incorrect","ExceptionMessage":"The function 'durableHelloHttpStart' doesn't exist, is disabled, or is not an orchestrator function. Additional info: The following are the known orchestrator functions: 'durableHelloOrchestrator'.","ExceptionType":"System.ArgumentException","StackTrace":" at Microsoft.Azure.WebJobs.Extensions.DurableTask.DurableTaskExtension.ThrowIfFunctionDoesNotExist(String name, FunctionType functionType) in D:\\a\\_work\\1\\s\\src\\WebJobs.Extensions.DurableTask\\DurableTaskExtension.cs:line 1338\r\n at Microsoft.Azure.WebJobs.Extensions.DurableTask.DurableClient.Microsoft.Azure.WebJobs.Extensions.DurableTask.IDurableOrchestrationClient.StartNewAsync[T](String orchestratorFunctionName, String instanceId, T input) in D:\\a\\_work\\1\\s\\src\\WebJobs.Extensions.DurableTask\\ContextImplementations\\DurableClient.cs:line 180\r\n at Microsoft.Azure.WebJobs.Extensions.DurableTask.HttpApiHandler.HandleStartOrchestratorRequestAsync(HttpRequestMessage request, String functionName, String instanceId) in D:\\a\\_work\\1\\s\\src\\WebJobs.Extensions.DurableTask\\HttpApiHandler.cs:line 875\r\n at Microsoft.Azure.WebJobs.Extensions.DurableTask.HttpApiHandler.HandleRequestAsync(HttpRequestMessage request) in D:\\a\\_work\\1\\s\\src\\WebJobs.Extensions.DurableTask\\HttpApiHandler.cs:line 306"} at DurableOrchestrationClient.createGenericError (C:\home\site\wwwroot\node_modules\durable-functions\lib\src\durableorchestrationclient.js:630:16) at DurableOrchestrationClient.<anonymous> (C:\home\site\wwwroot\node_modules\durable-functions\lib\src\durableorchestrationclient.js:419:44) at Generator.next (<anonymous>) at fulfilled (C:\home\site\wwwroot\node_modules\durable-functions\lib\src\durableorchestrationclient.js:5:58) at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by lilyjma** [comment]
Never mind! I figured out what I did wrong!
