### ISSUE TITLE
[JS] Getting orchestrator output exception when orchestrator returns undefined

### ISSUE THREAD

**Issue by cliffkoh** [Azure/azure-functions-durable-js#61]
All my orchestrations (which return `true` or `false`) have the following output entry in the "Instances" Azure Storage table.

```
Orchestrator function 'orchestrator' failed: TypeError: Cannot convert undefined or null to object    
	at hasOwnProperty (<anonymous>)    at Orchestrator.shouldFinish (C:\git\test\node_modules\durable-functions\lib\src\orchestrator.js:380:48)    
	at Orchestrator.<anonymous> (C:\git\test\node_modules\durable-functions\lib\src\orchestrator.js:64:30)    at Generator.next (<anonymous>)    
	at C:\git\test\node_modules\durable-functions\lib\src\orchestrator.js:7:71    
	at new Promise (<anonymous>)    
	at __awaiter (C:\git\test\node_modules\durable-functions\lib\src\orchestrator.js:3:12)    
	at Orchestrator.handle (C:\git\test\node_modules\durable-functions\lib\src\orchestrator.js:22:16)    
	at C:\git\test\node_modules\durable-functions\lib\src\shim.js:8:9    
	at WorkerChannel.invocationRequest (C:\Users\clkoh\AppData\Roaming\nvm\v8.11.3\node_modules\azure-functions-core-tools\bin\workers\node\worker-bundle.js:28866:26)
```

This corresponds to https://github.com/Azure/azure-functions-durable-js/blob/dd5c6765889da1b224576f3d37f14ae2cd53286d/src/orchestrator.ts#L530

This is a little baffling but does not actually block anything since I am not dependent on the output at the moment :)

**Comment by kashimiz** [comment]
Thanks for reporting this issue, @cliffkoh. It looks like a missing corner case that can be solved by a simple check. Can you provide a sample orchestration that reproduces this error?

**Comment by cliffkoh** [comment]
Hi @kashimiz, I just double checked my code and the way to repro this is just have an orchestration that returns a string, e.g. `return "Successful"`.

I think it is quite possible this repros with any primitive return value though that isn't an object (such as an array).

**Comment by cliffkoh** [comment]
@kashimiz just to confirm if you have all the information you need?

**Comment by cliffkoh** [comment]
This is becoming a much bigger issue in the latest version of the NPM package and extension host.. everyone of this is now surfacing as an exception in the app where previously it did not.

Could this please be fixed?

**Comment by cliffkoh** [comment]
Update: we debugged and figured this happens whenever an orchestrator returns undefined (or does not return a value).
